# Generated by Django 3.2.8 on 2021-10-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='hiragana_score',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='score',
            name='katakana_score',
            field=models.JSONField(default={}),
        ),
    ]
