# Generated by Django 3.2.8 on 2021-10-14 05:48

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211014_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='hiragana_score',
            field=models.JSONField(default=collections.defaultdict),
        ),
        migrations.AlterField(
            model_name='score',
            name='katakana_score',
            field=models.JSONField(default=collections.defaultdict),
        ),
    ]
