# Generated by Django 3.2.8 on 2021-10-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comments_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
